// packages/svelte/src/lib/components/nerd-labs/Approve.svelte
<script lang="ts">
  import { ethers } from "ethers";
  import { onMount } from "svelte";
  import { useScaffoldWriteContract } from "../../hooks/scaffold-eth";

  export let onApproveSuccess: () => void;

  const contractName = "RebaseToken";
  const spender = "0x..."; // Replace with the actual spender address
  const amount = ethers.MaxUint256;

  let writeContractAsync;
  let isMining = false;

  onMount(async () => {
    const { writeContractAsync: writeContract, isMining: mining } = await useScaffoldWriteContract(contractName);
    writeContractAsync = writeContract;
    isMining = mining;
  });

  async function handleApprove() {
    const variables = {
      functionName: "approve",
      args: [spender, amount],
    };

    if (writeContractAsync) {
      await writeContractAsync(variables);
      onApproveSuccess();
    }
  }
</script>

<button class="btn btn-primary" on:click={handleApprove} disabled={isMining}>
  {#if isMining}
    <span class="loading loading-spinner loading-sm"></span>
  {:else}
    Approve
  {/if}
</button>

// packages/nextjs/components/nerd-labs/Approve.tsx
import externalContracts from "../../contracts/deployedContracts";
import { ethers } from "ethers";
import { useScaffoldWriteContract } from "~~/hooks/scaffold-eth/";

interface Erc20FarmApproveProps {
  onApproveSuccess: () => void;
}

export function Approve({ onApproveSuccess }: Erc20FarmApproveProps) {
  const contractName = "RebaseToken";
  const spender = externalContracts[31337].RebaseToken.address;
  const amount = ethers.MaxUint256;

  // Adjusted to match the expected hook usage
  const { writeContractAsync, isMining } = useScaffoldWriteContract(contractName);

  const handleApprove = async () => {
    // Constructing the variables parameter correctly
    const variables = {
      functionName: "approve" as const, // Explicitly typing as a literal type
      args: [spender as string, amount] as const,
    };

    if (writeContractAsync) {
      await writeContractAsync(variables);
      onApproveSuccess();
    }
  };

  return (
    <button className="btn btn-primary" onClick={handleApprove} disabled={isMining}>
      {isMining ? <span className="loading loading-spinner loading-sm"></span> : "Approve"}
    </button>
  );
}

export function WrapCBDC(args: { balance: bigint; fName: string; onApproveSuccess: ERC20ApproveProps }) {
  const contractName = "WBOB";
  //const spender = externalContracts[31337].WBOB.address;
  //const amount = ethers.MaxUint256;
  // Adjusted to match the expected hook usage
  const { writeContractAsync, isMining } = useScaffoldWriteContract(contractName);
  const { fName: functionName, balance } = args;
  console.log(functionName);

  const handleApprove = async () => {
    // Constructing the variables parameter correctly
    const variables = {
      functionName: functionName.toString(),
      args: [balance] as const,
    };

    if (writeContractAsync) {
      await writeContractAsync(variables);
      args.onApproveSuccess();
    }
  };

  return (
    <button className="btn btn-primary" onClick={handleApprove} disabled={isMining}>
      {isMining ? (
        <span className="loading loading-spinner loading-sm"></span>
      ) : functionName == "deposit" ? (
        "Wrap 1"
      ) : (
        "Burn 1"
      )}
    </button>
  );
}
