// packages/nextjs/components/Farm.tsx
import LiquidityFarming from "./nerd-labs/LiquidityFarming";
import Staking from "./nerd-labs/Staking";
import BankOfBased from "~~/components/BankOfBased";
import MintBurn from "~~/components/MintBurn";

const Farm = () => {
  const stakingConfig = {
    tokenContractName: "MyToken",
    tokenAddress: "0x...",
    stakingPoolName: "Wrapped CBDC Staking",
    stakingPoolAddress: "0x...",
    tokenSymbol: "WCBDC",
    tokenDecimals: 18,
  };

  const daiUsdcConfig = {
    farmName: "WCBDC/ETH",
    tokenContractName: "WCBDCETHLP",
    farmContractName: "WCDBCETHFarm",
    tokenSymbol: "WCDBC/ETH-UniV2",
    rewardSymbol: "WCDBC",
    tokenDecimals: 18,
    rewardDecimals: 18,
  };

  const OptionalFarmEarningsComponent = () => {
    return <p>lmao</p>;
  };
  return (
    <>
    <div className="w-full md:w-auto">
      <div className="collapse bg-base-200 border border-gray-300 mx-6 w-full md:w-auto">
        <input type="radio" name="my-accordion-1" defaultChecked />
        <div className="collapse-title text-xl font-medium">INFO</div>
        <div className="collapse-content flex flex-col space-x-2 justify-center w-full md:w-auto">
          <BankOfBased />
        </div>
      </div>
      <div className="collapse bg-base-200 border border-gray-300 mx-6 w-full md:w-auto">
        <input type="radio" name="my-accordion-1" />
        <div className="collapse-title text-xl font-medium">WCBDC Staking</div>
        <div className="collapse-content flex flex-col space-x-2 justify-center w-full md:w-auto">
          <MintBurn />
        </div>
      </div>
      <div className="collapse bg-base-200 border border-gray-300 mx-6 w-full md:w-auto">
        <input type="radio" name="my-accordion-1" />
        <div className="collapse-title text-xl font-medium">FARMS</div>
        <div className="collapse-content flex flex-row space-x-12 p-4 justify-center w-full md:w-auto">
          <Staking config={stakingConfig} FarmEarnings={OptionalFarmEarningsComponent} />
          <LiquidityFarming config={daiUsdcConfig} />
        </div>
      </div>
    </div>
    </>
  );
};

export default Farm;

// packages/svelte/src/lib/components/nerd-labs/Farm.svelte
<script>
  import { createAccount } from "@byteatatime/wagmi-svelte";
  import LiquidityFarming from "./LiquidityFarming.svelte";
  // import BankOfBased from "./BankOfBased.svelte";
  import MintBurn from "./MintBurn.svelte";

  const account = $derived.by(createAccount());

  const stakingConfig = {
    tokenContractName: "MyToken",
    tokenAddress: "0x...",
    stakingPoolName: "Wrapped CBDC Staking",
    stakingPoolAddress: "0x...",
    tokenSymbol: "WCBDC",
    tokenDecimals: 18,
  };

  const daiUsdcConfig = {
    farmName: "WCBDC/ETH",
    tokenContractName: "WCBDCETHLP",
    farmContractName: "WCDBCETHFarm",
    tokenSymbol: "WCDBC/ETH-UniV2",
    rewardSymbol: "WCDBC",
    tokenDecimals: 18,
    rewardDecimals: 18,
  };

  const OptionalFarmEarningsComponent = () => {
    return "<p>lmao</p>";
  };
</script>

<div class="w-full md:w-auto">
  <div class="collapse mx-6 w-full border border-gray-300 bg-base-300 md:w-auto">
    <input type="radio" name="my-accordion-1" checked />
    <div class="collapse-title cursor-pointer text-xl font-medium">WCBDC Staking</div>
    <div class="collapse-content flex w-full flex-col justify-center space-x-2 md:w-auto">
      <MintBurn />
    </div>
  </div>
  <div class="collapse mx-6 w-full border border-gray-300 bg-base-300 md:w-auto">
    <input type="radio" name="my-accordion-1" />
    <div class="collapse-title cursor-pointer text-xl font-medium">FARMS</div>
    <div class="collapse-content flex w-full flex-row justify-center space-x-12 p-4 md:w-auto">
      <LiquidityFarming config={daiUsdcConfig} />
    </div>
  </div>
  <div class="collapse mx-6 w-full border border-gray-300 bg-base-300 md:w-auto">
    <input type="radio" name="my-accordion-1" />
    <div class="collapse-title cursor-pointer text-xl font-medium">INFO</div>
    <div class="collapse-content flex w-full flex-col justify-center space-x-2 md:w-auto"></div>
  </div>
</div>
