// packages/nextjs/components/MintBurn.tsx
import { useEffect, useState } from "react";
import { Approve, WrapCBDC } from "./nerd-labs/Approve.tsx";
import { useAccount } from "wagmi";
import { useScaffoldReadContract } from "~~/hooks/scaffold-eth";

const MintBurn = () => {
  const [percentages, setPercentages] = useState({ cBDC: 100n, wBOB: 100n });
  const [balances, setBalances] = useState({ cBDC: 0n, wBOB: 0n });
  const [customPercentage, setCustomPercentage] = useState("");

  const account = useAccount();
  const treasury = "0xf39fd6e51aad88f6f4ce6ab8827279cfffb92266";
  const balanceRead = useScaffoldReadContract({
    contractName: "RebaseToken",
    functionName: "balanceOf",
    args: [account.address],
  });
  const tBalanceRead = useScaffoldReadContract({
    contractName: "RebaseToken",
    functionName: "balanceOf",
    args: [treasury],
  });
  const t2BalanceRead = useScaffoldReadContract({
    contractName: "WBOB",
    functionName: "balanceOf",
    args: [treasury],
  });

  const wrappedBalanceRead = useScaffoldReadContract({
    contractName: "WBOB",
    functionName: "balanceOf",
    args: [account.address],
  });

  const taxRate = useScaffoldReadContract({
    contractName: "WBOB",
    functionName: "_taxRate",
    args: [],
  });

  useEffect(() => {
    if (balanceRead.data) {
      setBalances(prev => ({ ...prev, cBDC: (balanceRead.data * percentages.cBDC) / 100n }));
    }
    if (wrappedBalanceRead.data) {
      setBalances(prev => ({ ...prev, wBOB: (wrappedBalanceRead.data * percentages.wBOB) / 100n }));
    }
  }, [balanceRead.data, wrappedBalanceRead.data, percentages]);

  const handlePercentageChange = (type, value) => {
    const newPercentage = BigInt(Math.min(Math.max(Number(value), 0), 100));
    setPercentages(prev => ({ ...prev, [type]: newPercentage }));
  };

  const renderPercentageButtons = type => {
    return [10, 25, 50, 75, 100].map(percent => (
      <button key={percent} className="btn" onClick={() => handlePercentageChange(type, percent)}>
        {percent}%
      </button>
    ));
  };

  return (
    <div className="card flex flex-col bg-base-100 w-96 md:w-auto">
      <div className="card-title flex-row w-full md:w-auto">
        <p className="stat">
          <span className="stat-title">CBDC Treasury Balance:</span>{" "}
          <span className="stat-value">{Number(tBalanceRead?.data) * 1e-9}</span>
        </p>
        <p className="stat">
          <span className="stat-title">WCBDC Treasury Balance:</span>
          <span className="stat-value"> {Number(t2BalanceRead?.data) * 1e-18}</span>
        </p>
        <p className="stat">
          <span className="stat-title">Tax Rate:</span> {taxRate?.data?.toString()}bps
        </p>
      </div>
      <div className="card-title p-12 flex flex-row w-full md:w-auto">
        {["cBDC", "wBOB"].map(type => (
          <div className="card-body flex flex-col" key={type}>
            <WrapCBDC
              onApproveSuccess={() => console.log(`${type} success`)}
              fName={type === "cBDC" ? "deposit" : "burn"}
              balance={balances[type]}
              percentage={percentages[type]}
              onPercentageChange={value => handlePercentageChange(type, value)}
            />
            <div className="flex flex-row">{renderPercentageButtons(type)}</div>
          </div>
        ))}
      </div>
      <div className="form-control w-full md:w-auto p-16">
        <Approve onApproveSuccess={() => console.log("Approved")} />
      </div>
    </div>
  );
};
export default MintBurn;

// packages/svelte/src/lib/components/nerd-labs/MintBurn.svelte
<script>
  import { createAccount, createContractRead } from "@byteatatime/wagmi-svelte";
  import { Approve, WrapCBDC } from "./nerd-labs/Approve.svelte";

  let percentages = $state({ cBDC: 100n, wBOB: 100n });
  let balances = $state({ cBDC: 0n, wBOB: 0n });
  let customPercentage = $state("");

  const { address } = $derived.by(createAccount());
  const treasury = "0xf39fd6e51aad88f6f4ce6ab8827279cfffb92266";

  const balanceRead = $derived.by(() =>
    createContractRead({
      contractName: "RebaseToken",
      functionName: "balanceOf",
      args: [address],
    })
  );

  const tBalanceRead = $derived.by(() =>
    createContractRead({
      contractName: "RebaseToken",
      functionName: "balanceOf",
      args: [treasury],
    })
  );

  const t2BalanceRead = $derived.by(() =>
    createContractRead({
      contractName: "WBOB",
      functionName: "balanceOf",
      args: [treasury],
    })
  );

  const wrappedBalanceRead = $derived.by(() =>
    createContractRead({
      contractName: "WBOB",
      functionName: "balanceOf",
      args: [address],
    })
  );

  const taxRate = $derived.by(() =>
    createContractRead({
      contractName: "WBOB",
      functionName: "_taxRate",
      args: [],
    })
  );

  $: {
    if (balanceRead.data) {
      balances.cBDC = (balanceRead.data * percentages.cBDC) / 100n;
    }
    if (wrappedBalanceRead.data) {
      balances.wBOB = (wrappedBalanceRead.data * percentages.wBOB) / 100n;
    }
  }

  function handlePercentageChange(type, value) {
    const newPercentage = BigInt(Math.min(Math.max(Number(value), 0), 100));
    percentages[type] = newPercentage;
  }

  function renderPercentageButtons(type) {
    return [10, 25, 50, 75, 100].map((percent) => (
      <button class="btn" on:click={() => handlePercentageChange(type, percent)}>
        {percent}%
      </button>
    ));
  }
</script>

<div class="card flex flex-col bg-base-100 w-96 md:w-auto">
  <div class="card-title flex-row w-full md:w-auto">
    <p class="stat">
      <span class="stat-title">CBDC Treasury Balance:</span>
      <span class="stat-value">{Number(tBalanceRead?.data) * 1e-9}</span>
    </p>
    <p class="stat">
      <span class="stat-title">WCBDC Treasury Balance:</span>
      <span class="stat-value">{Number(t2BalanceRead?.data) * 1e-18}</span>
    </p>
    <p class="stat">
      <span class="stat-title">Tax Rate:</span> {taxRate?.data?.toString()}bps
    </p>
  </div>
  <div class="card-title p-12 flex flex-row w-full md:w-auto">
    {#each ["cBDC", "wBOB"] as type}
      <div class="card-body flex flex-col">
        <WrapCBDC
          on:approveSuccess={() => console.log(`${type} success`)}
          fName={type === "cBDC" ? "deposit" : "burn"}
          balance={balances[type]}
          percentage={percentages[type]}
          on:percentageChange={(value) => handlePercentageChange(type, value)}
        />
        <div class="flex flex-row">
          {renderPercentageButtons(type)}
        </div>
      </div>
    {/each}
  </div>
  <div class="form-control w-full md:w-auto p-16">
    <Approve on:approveSuccess={() => console.log("Approved")} />
  </div>
</div>
