// packages/svelte/src/lib/components/Footer.svelte
<script>
  import { nativeCurrencyPrice } from "$lib/runes/global.svelte";
  import { createTargetNetwork } from "$lib/runes/targetNetwork.svelte";
  import BuidlGuidlLogo from "./assets/BuidlGuidlLogo.svelte";
  import { CurrencyDollar, Heart, Icon, MagnifyingGlass } from "svelte-hero-icons";
  import { hardhat } from "viem/chains";
  import Faucet from "./scaffold-eth/Faucet.svelte";
  import SwitchTheme from "./SwitchTheme.svelte";

  const targetNetwork = $derived.by(createTargetNetwork());
  const isLocalNetwork = $derived(targetNetwork.id === hardhat.id);
</script>

<div class="mb-11 min-h-0 px-1 py-5 lg:mb-0">
  <div>
    <div class="pointer-events-none fixed bottom-0 left-0 z-10 flex w-full items-center justify-between p-4">
      <div class="pointer-events-auto flex flex-col gap-2 md:flex-row">
        {#if nativeCurrencyPrice.price > 0}
          <div>
            <div class="btn btn-primary btn-sm cursor-auto gap-1 font-normal">
              <Icon src={CurrencyDollar} class="h-4 w-4" />
              <span>{nativeCurrencyPrice.price}</span>
            </div>
          </div>
        {/if}
        {#if isLocalNetwork}
          <Faucet />
          <a href="/blockexplorer" class="btn btn-primary btn-sm gap-1 font-normal">
            <Icon src={MagnifyingGlass} class="h-4 w-4" />
            <span>Block Explorer</span>
          </a>
        {/if}
      </div>
      <SwitchTheme class="pointer-events-auto {isLocalNetwork && 'self-end md:self-auto'}" />
    </div>
  </div>
  <div class="w-full">
    <ul class="menu menu-horizontal w-full">
      <div class="flex w-full items-center justify-center gap-2 text-sm">
        <div class="text-center">
        </div>

        <div class="flex items-center justify-center gap-2">
        </div>
   
        <div class="text-center">
        
        </div>
      </div>
    </ul>
  </div>
</div>

// packages/nextjs/components/Footer.tsx
import React from "react";
import Link from "next/link";
import { hardhat } from "viem/chains";
import { CurrencyDollarIcon, MagnifyingGlassIcon } from "@heroicons/react/24/outline";
import { HeartIcon } from "@heroicons/react/24/outline";
import { SwitchTheme } from "~~/components/SwitchTheme";
import { BuidlGuidlLogo } from "~~/components/assets/BuidlGuidlLogo";
import { Faucet } from "~~/components/scaffold-eth";
import { useTargetNetwork } from "~~/hooks/scaffold-eth/useTargetNetwork";
import { useGlobalState } from "~~/services/store/store";

/**
 * Site footer
 */
export const Footer = () => {
  const nativeCurrencyPrice = useGlobalState(state => state.nativeCurrency.price);
  const { targetNetwork } = useTargetNetwork();
  const isLocalNetwork = targetNetwork.id === hardhat.id;

  return (
    <div className="min-h-0 py-5 px-1 mb-11 lg:mb-0">
      <div>
        <div className="fixed flex justify-between items-center w-full z-10 p-4 bottom-0 left-0 pointer-events-none">
          <div className="flex flex-col md:flex-row gap-2 pointer-events-auto">
            {nativeCurrencyPrice > 0 && (
              <div>
                <div className="btn btn-primary btn-sm font-normal gap-1 cursor-auto">
                  <CurrencyDollarIcon className="h-4 w-4" />
                  <span>{nativeCurrencyPrice.toFixed(2)}</span>
                </div>
              </div>
            )}
            {isLocalNetwork && (
              <>
                <Faucet />
                <Link href="/blockexplorer" passHref className="btn btn-primary btn-sm font-normal gap-1">
                  <MagnifyingGlassIcon className="h-4 w-4" />
                  <span>Block Explorer</span>
                </Link>
              </>
            )}
          </div>
          <SwitchTheme className={`pointer-events-auto ${isLocalNetwork ? "self-end md:self-auto" : ""}`} />
        </div>
      </div>
      <div className="w-full">
        <ul className="menu menu-horizontal w-full">
          <div className="flex justify-center items-center gap-2 text-sm w-full">
            <div className="text-center">
              <a href="https://github.com/NERDDAO/bob" target="_blank" rel="noreferrer" className="link">
                Fork me
              </a>
            </div>
            <span>·</span>
            <div className="flex justify-center items-center gap-2">
              {" "}
              Made with <span className="text-red-500">{"<3"}</span> by <span className="text-black">Plat0x.eth </span>
              and the <span className="text-green-500">N</span>
              <span className="text-red-500">E</span>
              <span className="text-yellow-200">R</span>
              <span className="text-purple-400">D</span>
              <span className="text-blue-500">S</span>{" "}
            </div>
            <span>·</span>
            <div className="text-center">
              <a href="https://t.me/thenerdlabs" target="_blank" rel="noreferrer" className="link">
                Support
              </a>
            </div>
          </div>
        </ul>
      </div>
    </div>
  );
};
